version: "3.1"
services:

  Notary:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.1-corda
    env_file:
      - ./corda_docker.env
    ports:
      - "10012:10002"
    image: corda/node:3.1
    container_name: notary
    volumes:
      - ./nodes/notary/node.conf:/opt/corda/node.conf
      - ./nodes/notary/certificates/:/opt/corda/certificates/
      - ./nodes/notary/network-parameters:/opt/corda/network-parameters
      - ./nodes/notary/additional-node-infos/:/opt/corda/additional-node-infos
    restart: always

  CordaNodeA:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.1-corda
    env_file:
      - ./corda_docker.env
    ports:
      - "10022:10002"
      - "10023:10003"
      - "10024:10004"
    image: corda/node:3.1
    container_name: banka
    volumes:
      - ./nodes/banka/node.conf:/opt/corda/node.conf
      - ./nodes/banka/cordapps/:/opt/corda/cordapps/
      - ./nodes/banka/certificates/:/opt/corda/certificates/
      - ./nodes/banka/network-parameters:/opt/corda/network-parameters
      - ./nodes/banka/additional-node-infos/:/opt/corda/additional-node-infos
    restart: always

  CordaNodeB:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.1-corda
    env_file:
      - ./corda_docker.env
    ports:
      - "10032:10002"
      - "10033:10003"
      - "10034:10004"
    image: corda/node:3.1
    container_name: bankb
    volumes:
      - ./nodes/bankb/node.conf:/opt/corda/node.conf
      - ./nodes/bankb/cordapps/:/opt/corda/cordapps/
      - ./nodes/bankb/certificates/:/opt/corda/certificates/
      - ./nodes/bankb/network-parameters:/opt/corda/network-parameters
      - ./nodes/bankb/additional-node-infos/:/opt/corda/additional-node-infos
    restart: always

  CordaNodeC:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.1-corda
    env_file:
      - ./corda_docker.env
    ports:
      - "10042:10002"
      - "10043:10003"
      - "10044:10004"
    image: corda/node:3.1
    container_name: bankc
    volumes:
      - ./nodes/bankc/node.conf:/opt/corda/node.conf
      - ./nodes/bankc/cordapps/:/opt/corda/cordapps/
      - ./nodes/bankc/certificates/:/opt/corda/certificates/
      - ./nodes/bankc/network-parameters:/opt/corda/network-parameters
      - ./nodes/bankc/additional-node-infos/:/opt/corda/additional-node-infos
    restart: always


networks:
  corda:
