version: "3.1"
services:
  CordaNotary:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.1-corda
    env_file:
      - ./corda_docker.env
    ports:
      - "10006:10002"
    image: corda/notary:3.1
    container_name: notary
    volumes:
      - ./nodes/notary/corda-notary.conf:/opt/corda/node.conf
      - ./nodes/notary/certificates:/opt/corda/certificates/
      - ./nodes/notary/network-parameters:/opt/corda/network-parameters
      - ./nodeinfos/:/opt/corda/additional-node-infos
      - ./dirvers/:/opt/corda/dirvers


  CordaNodeA:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.1-corda
    env_file:
      - ./corda_docker.env
    ports:
      - "10007:10002"
      - "10008:10003"
      - "10009:10004"
      - "10048:10005"
    image: corda/notary:3.1
    container_name: partya
    volumes:
      - ./nodes/partya/node.conf:/opt/corda/node.conf
      - ./nodes/partya/network-parameters:/opt/corda/network-parameters
      - ./cordapps/:/opt/corda/cordapps/
      - ./nodes/partya/certificates/:/opt/corda/certificates/
      - ./nodeinfos/:/opt/corda/additional-node-infos
      - ./dirvers/:/opt/corda/dirvers
    depends_on:
      - CordaNotary
    restart: always

  CordaNodeB:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.1-corda
    env_file:
      - ./corda_docker.env
    ports:
      - "10010:10002"
      - "10011:10003"
      - "10012:10004"
      - "10051:10005"
    image: corda/notary:3.1
    container_name: PartyB
    volumes:
      - ./nodes/PartyB/node.conf:/opt/corda/node.conf
      - ./nodes/PartyB/network-parameters:/opt/corda/network-parameters
      - ./cordapps/:/opt/corda/cordapps/
      - ./nodes/PartyB/certificates/:/opt/corda/certificates/
      - ./nodeinfos/:/opt/corda/additional-node-infos
      - ./dirvers/:/opt/corda/dirvers
    depends_on:
      - CordaNotary
    restart: always

  CordaNodeC:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.1-corda
    env_file:
      - ./corda_docker.env
    ports:
      - "10013:10002"
      - "10014:10003"
      - "10015:10004"
      - "10054:10005"
    image: corda/notary:3.1
    container_name: PartyC
    volumes:
      - ./nodes/PartyC/node.conf:/opt/corda/node.conf
      - ./nodes/PartyC/network-parameters:/opt/corda/network-parameters
      - ./cordapps/:/opt/corda/cordapps/
      - ./nodes/PartyC/certificates/:/opt/corda/certificates/
      - ./nodeinfos/:/opt/corda/additional-node-infos
      - ./dirvers/:/opt/corda/dirvers
    depends_on:
      - CordaNotary
    restart: always


networks:
  corda:
